name: Manual & Shared Workflow
on:
  workflow_dispatch:
    inputs:
      choice-example:
        description: Choice Example
        required: true
        default: warning
        type: choice
        options:
          - warning
          - error
          - success
          - failure
      string-example:
        description: String Example
        required: true
        default: input
        type: string
  workflow_call:
    inputs:
      choice-example:
        description: Choice Example
        required: true
        default: warning
        type: string
      string-example:
        description: String Example
        required: true
        default: input
        type: string
jobs:
  do-things:
    name: Do things Manually
    runs-on: ubuntu-latest
    steps:
      - name: Do a thing
        run: echo "I've done a thing manually with ''"
